version: "3.8"

networks:
  web:
    external: true
  internal:
    external: false

volumes:
  contagem_mongo_data:

services:
  contagem:
    container_name: "contagem_de_ciclistas_api"
    restart: always
    build: .
    image: ameciclo/contagem_de_ciclistas
    environment:
      PORT: 4000
      MONGO_DB: contagem
      MONGO_HOSTNAME: mongodb
      MONGO_PORT: 27017
      MONGO_USERNAME: ameciclo
      MONGO_PASSWORD: ameciclo
      NODE_ENV: "${ENV}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.contagem.rule=Host(`api.plataforma.ameciclo.org`) && PathPrefix(`/contagens/v1/`)"
      - "traefik.http.routers.contagem.tls.certresolver=le"
      - "traefik.http.middlewares.redirectscheme.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirectscheme.redirectscheme.permanent=true"
      - "traefik.docker.network=web"
    networks:
      - internal
      - web
    ports:
      - "4000:4000"
    links:
      - mongodb
  mongodb:
    container_name: "contagem_de_ciclistas_mongodb"
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ameciclo
      MONGO_INITDB_ROOT_PASSWORD: ameciclo
    ports:
      - "27017:27017"
    networks:
      - internal
    labels:
      - traefik.enable=false
    volumes:
      - contagem_mongo_data:/data/db
